title: Eslam Atia
logo: /assets/img/logo.jpg
description: ğŸ“ +201004742088 âœ‰ï¸ eslam.mo.atia@gmail.com  ğŸ”— [LinkedIn](https://linkedin.com/in/ekor) | [GitHub](https://github.com/ekorayem)

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
