title: Eslam Atia
logo: /assets/img/logo.jpg
description: test
# ğŸ“ +201004742088 âœ‰ï¸ eslam.mo.atia@gmail.com  ğŸ”— [LinkedIn](https://linkedin.com/in/ekor) | [GitHub](https://github.com/ekorayem)
incremental: false
lsi: false
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
